# Site settings
title: Image Resizer for Windows
description: Lets you resize images by right-clicking
author:
  name: Brice Lambson
  twitter: bricelambs
logo: /images/icon.png
google_analytics_tracking_id: UA-57792437-2

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag
gist:
  noscript: false
kramdown:
  hard_wrap: false
  input: GFM
